# Generated by Django 5.2.13 on 2026-04-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multicontent', '0002_alter_multimediaasset_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='multimedia',
            field=models.ManyToManyField(blank=True, related_name='contents', to='multicontent.multimediaasset'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='multimedia',
            field=models.ManyToManyField(blank=True, related_name='articles', to='multicontent.multimediaasset'),
        ),
    ]
