# Generated by Django 6.0.4 on 2026-04-13 04:46

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multicontent', '0003_content_multimedia_newsarticle_multimedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='multimedia',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='multimedia',
        ),
        migrations.AlterField(
            model_name='content',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
