# Generated by Django 5.2.7 on 2025-11-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
